### PR TITLE
specifying terra::prod() causes error

### PR DESCRIPTION
**Pull request by benjaminmisiuk**

### CODE REVIEW

**Comment by ailich** [comment]
@benjaminmisiuk, `terra::prod` should work if you update `terra` (see last comment of the link below).

https://github.com/ailich/GLCMTextures/issues/15

**Comment by benjaminmisiuk** [comment]
Thanks. I had tried re-installed this morning:

```
remotes::install_github("rspatial/terra")
library(terra) #v. 1.5-20

r <- rast(volcano)
terra::prod(r, 4)

#Error: 'prod' is not an exported object from 'namespace:terra'

prod(r, 4)
```
Seems like we could just leave out specifying terra:: and it should work fine?

**Comment by ailich** [comment]
Does `atan_2(rast(volcano), rast(volcano))` run for you? (Note: `atan_2` not `atan2`).

**Comment by ailich** [comment]
Actually, I'm no longer seeing `terra::prod` anymore after updating. I guess it got added and accidentally removed? I'll just remove the `terra::` part as you suggested.

**Pull request merged**
